### ISSUE TITLE
Allow for more than 2 FBAs in allocation of an FBS activity set

### ISSUE THREAD

**Issue by catherinebirney** [USEPA/flowsa#149]
Current method only allows for "allocation_source" and "helper_source" FBAs for FBS activity set allocation. Modify the FBS yaml to allow for unlimited FBAs to be called for allocation. Changing methodology will make methodology more transparent and limit the number of FBAs hardcoded into cleaning functions.

**Comment by catherinebirney** [comment]
@WesIngwersen @bl-young @matthewlchambers

See [water m3](https://github.com/USEPA/flowsa/blob/fbs_yaml_refac/flowsa/data/flowbysectormethods/Water_national_2015_m3.yaml) for initial refactoring efforts. These changes will require an additional function for the "disaggregation" method created in activity set 4. I also expect the formatting to change once I start modifying the code. Let me know your thoughts.

**Comment by matthewlchambers** [comment]
I've had some thoughts on this. I think that this issue can be addressed, and the code quite a bit simplified, by allowing for recursion in the definition of our configuration `yaml`s, and in the code that attributes FBA flows to sectors. Basically, I note that what the helper FBAs are doing is allocating the flows of an FBA which will be used to allocate the flows of an FBA, etc. So, what I'm suggesting is something like this
```
source_names:
  EPA_NEI_Nonpoint:
      industry_combustion_coal_activity_set:
        names: !from_index:NEI_Nonpoint_2017_asets.csv industry_combustion_coal
        allocation_method: proportional
        allocation_source:
          EIA_MECS_Energy:
            class: Energy
            year: 2014
            geoscale: national
            flows:
              - Coal
            clean_fba_df_fxn: !script_function:EIA_MECS mecs_energy_fba_cleanup
            clean_fba_w_sec_df_fxn: !script_function:EIA_MECS eia_mecs_energy_clean_allocation_fba_w_sec
            allocation_method: proportional
            allocation_source:
              BLS_QCEW:
                class: Employment
                year: 2014
                geoscale: national
                flows: None
                allocation_method: direct
                clean_fba_df_fxn: !script_function:BLS_QCEW clean_bls_qcew_fba
                clean_fba_wsec_df_fxn: !script_function:BLS_QCEW bls_clean_allocation_fba_w_sec
```
with corresponding recursion allowed in the code, as follows (this is illustrative pseudo-code, since I haven't implemented yet), with the recursive call to `create_fba_with_sectors()` as the second argument passed to `proportional_allocation()`:
```
def create_fba_with_sectors(source_name, source_config, geoscale, naics_level):
    source_fba = get_fba(source_name)
    fba_at_geoscale = convert_to_geoscale(source_fba, geoscale)
    if 'clean_fba_df_fxn' in source_config:
        fba_at_geoscale = source_config['clean_fba_df_fxn'](fba_at_geoscale)
    fba_with_sectors = map_to_sectors(fba_at_geoscale, naics_level)
    if 'clean_fba_wsec_df_fxn' in source_config:
        fba_with_sectors = source_config['clean_fba_df_fxn'](fba_with_sectors)

    if source_config['allocation_method'] == 'direct'
        allocated_fba = direct_allocation(fba_with_sectors)
    elif source_config['allocation_method'] == 'proportional'
        allocation_source_name = source_config['allocation_source']
        allocated_fba = proportional_allocation(
            fba_with_sectors,
            create_fba_with_sectors(
                allocation_source_name,
                source_config['allocation_source'][allocation_source_name],
                geoscale,
                naics_level
            )
        )

    return allocated_fba
```
Note that this also allows me to take three different keys (e.g. `clean_fba_df_fxn`, `clean_allocation_fba`, `clean_helper_fba`), handled in three separate places in the code, and use a single key handled at a single place in the code instead.
